{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "489a9fe0",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\hp\\anaconda3\\Lib\\site-packages\\pandas\\core\\arrays\\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).\n",
      "  from pandas.core import (\n",
      "2026-05-06 16:09:43.104 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\hp\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import xgboost as xgb\n",
    "import shap\n",
    "import matplotlib.pyplot as plt\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.model_selection import train_test_split\n",
    "\n",
    "# 1. Configure the Web Page\n",
    "st.set_page_config(page_title=\"Phishing Detection Framework\", layout=\"wide\")\n",
    "st.title(\"🛡️ Explainable Ensemble Phishing Detection\")\n",
    "st.markdown(\"### Proactive Zero-Day Threat Analysis | M.Tech Research Demo\")\n",
    "st.divider()\n",
    "\n",
    "# 2. Background Processing (Cached so it runs instantly)\n",
    "@st.cache_resource\n",
    "def load_and_train_model():\n",
    "    data = pd.read_csv(\"uci_phishing.csv\")\n",
    "    X = data.drop('Result', axis=1) \n",
    "    y = data['Result'].replace(-1, 0) # The XGBoost Fix\n",
    "    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n",
    "    \n",
    "    rf_model = RandomForestClassifier(n_estimators=100, random_state=42)\n",
    "    xgb_model = xgb.XGBClassifier(eval_metric='logloss')\n",
    "    rf_model.fit(X_train, y_train)\n",
    "    xgb_model.fit(X_train, y_train)\n",
    "    \n",
    "    return rf_model, xgb_model, X_test, y_test\n",
    "\n",
    "# Load the engine silently\n",
    "rf_model, xgb_model, X_test, y_test = load_and_train_model()\n",
    "\n",
    "# 3. The Dashboard Interface\n",
    "st.sidebar.header(\"Control Panel\")\n",
    "st.sidebar.write(\"Click below to intercept and analyze a new URL payload from the data stream.\")\n",
    "\n",
    "if st.sidebar.button(\"🔍 Simulate Live URL Scan\", type=\"primary\"):\n",
    "    \n",
    "    # Grab a random URL's features from the unseen test set\n",
    "    sample_idx = np.random.randint(0, len(X_test))\n",
    "    sample_features = X_test.iloc[[sample_idx]]\n",
    "    actual_truth = y_test.iloc[sample_idx]\n",
    "    \n",
    "    # Run the Fusion Layer\n",
    "    rf_probs = rf_model.predict_proba(sample_features)\n",
    "    xgb_probs = xgb_model.predict_proba(sample_features)\n",
    "    avg_probs = (rf_probs + xgb_probs) / 2\n",
    "    \n",
    "    prediction = np.argmax(avg_probs, axis=1)[0]\n",
    "    confidence = np.max(avg_probs) * 100\n",
    "    \n",
    "    # 4. Display Results\n",
    "    col1, col2 = st.columns(2)\n",
    "    \n",
    "    with col1:\n",
    "        st.subheader(\"Diagnostic Output\")\n",
    "        if prediction == 0:\n",
    "            st.error(f\"🚨 **PHISHING DETECTED**\")\n",
    "            st.write(f\"**Threat Confidence:** {confidence:.2f}%\")\n",
    "        else:\n",
    "            st.success(f\"✅ **LEGITIMATE SITE**\")\n",
    "            st.write(f\"**Safety Confidence:** {confidence:.2f}%\")\n",
    "            \n",
    "        actual_text = \"Phishing\" if actual_truth == 0 else \"Legitimate\"\n",
    "        st.info(f\"**Ground Truth Verification:** This site is actually {actual_text}.\")\n",
    "        \n",
    "    with col2:\n",
    "        st.subheader(\"🧠 SHAP Reason Codes\")\n",
    "        st.write(\"Top structural indicators driving this specific decision:\")\n",
    "        \n",
    "        # Generate the Explainability Plot on the fly\n",
    "        explainer = shap.TreeExplainer(xgb_model)\n",
    "        shap_values = explainer.shap_values(sample_features)\n",
    "        \n",
    "        fig, ax = plt.subplots(figsize=(6, 4))\n",
    "        shap.summary_plot(shap_values, sample_features, plot_type=\"bar\", show=False)\n",
    "        st.pyplot(fig)\n",
    "else:\n",
    "    st.info(\"👈 System Ready. Initiate a scan from the Control Panel.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3214d5d6",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
